1:
		g++ project1.cpp -std=c++11 -o a
2:
		g++ project2.cpp -std=c++11 -o a
3:
		g++ project3.cpp -std=c++11 -o a
4:
		g++ project4.cpp -std=c++11 -o a
5:
		g++ project5.cpp -std=c++11 -o a
nc:
		g++ nc.cpp -std=c++17 -o a
